#include "metal_vm.h"

static void uart_putchar(char c) {
    // UART0 for QEMU 'virt' machine
    volatile unsigned int* uart = (unsigned int*)0x09000000;
    *uart = c;
}

// Minimal libc stubs for freestanding environment
void* memset(void* s, int c, unsigned long n) {
    unsigned char* p = (unsigned char*)s;
    while (n--) *p++ = (unsigned char)c;
    return s;
}

void* memcpy(void* dest, const void* src, unsigned long n) {
    unsigned char* d = (unsigned char*)dest;
    const unsigned char* s = (const unsigned char*)src;
    while (n--) *d++ = *s++;
    return dest;
}

unsigned long strlen(const char* s) {
    unsigned long n = 0;
    while (s[n]) n++;
    return n;
}

int strcmp(const char* s1, const char* s2) {
    while (*s1 && *s1 == *s2) { s1++; s2++; }
    return (int)(unsigned char)*s1 - (int)(unsigned char)*s2;
}

static void vm_write_char(char c) {
    uart_putchar(c);
}

// Symbols generated by objcopy for the kernel bytecode
extern unsigned char _binary_build_kernel_sgvm_start[];
extern unsigned char _binary_build_kernel_sgvm_end[];

MetalVM g_vm;

void kmain(void) {
    uart_putchar('H'); uart_putchar('E'); uart_putchar('L'); uart_putchar('L'); uart_putchar('O'); uart_putchar('\n');

    metal_vm_init(&g_vm);
    g_vm.write_char = vm_write_char;

    unsigned char* start = _binary_build_kernel_sgvm_start;
    unsigned char* end = _binary_build_kernel_sgvm_end;
    int size = (int)(end - start);

    if (size > 0 && metal_vm_load_binary(&g_vm, start, size) == 0) {
        if (metal_vm_verify(&g_vm) == 0) {
            for (int i = 0; i < g_vm.chunk_count; i++) {
                metal_vm_load(&g_vm, g_vm.chunks[i], g_vm.chunk_lengths[i]);
                metal_vm_run(&g_vm);
            }
        }
    }

    while (1) {
        __asm__ volatile ("wfi");
    }
}
